Delete Button
CS3219-AY2425S1/cs3219-ay2425s1-project-g24 pull request #12
Opened 2024-09-26 09:05 UTC by chiaryan

Also:
- Functionality to delete a question from database
- modal for confirming to delete a question

2024-09-26 09:30 UTC, solomonng2001 commented
I've changed the target branch to staging.

2024-09-27 15:26 UTC, bensohh requested changes
most of it looks good, look into how we can utilise the docRefId directly rather than reference the id then isolate the docRefId. Resolve the conflicts and I think it should be good to go.

2024-09-27 15:26 UTC, bensohh commented on apps/question-service/src/app/page.tsx
> +            }
For this right, instead of id for dataindex you can directly set it as the docRefId so you don't have to do a manual loop of O(n) through all the questions to find the right index and work with the docRefId straight away. Passing the docRefId to your async function to delete the data

2024-09-27 15:26 UTC, bensohh commented on apps/question-service/src/app/page.tsx
> +  useEffect(() => {loadQuestions()}, [limit, currentPage]);
I think there are some code conflicts here since the staging branch has been updated, perhaps you would want to look into the new changes and integrate them locally or on github if u prefer

2024-09-27 15:26 UTC, bensohh commented on apps/question-service/src/app/page.tsx
> +    if (currentPage == undefined) {
The currentPage useState defaults to 1 in the new staging branch so this might not be required?

2024-09-27 15:26 UTC, bensohh commented on apps/question-service/src/app/page.tsx
> +  };
Can consider using the success or error component above to prompt the user on a message that pops up when they successfully delete the data or some error occured :)

2024-09-28 05:06 UTC, bensohh approved these changes
LGTM 👍🏻

2024-09-28 13:44 UTC, merged