feat: Implement Profile Page
CS3219-AY2425S1/cs3219-ay2425s1-project-g24 pull request #27
Opened 2024-10-05 03:15 UTC by bensohh

- Add menu to display profile page
- Add logout logic
- Add updating profile page logic

2024-10-05 16:24 UTC, chiaryan requested changes
Hi,

Good job on the profile page, I think you need to take another look at how edit cancelling works

2024-10-05 16:24 UTC, chiaryan commented on apps/frontend/src/app/profile/page.tsx
> +                    <Input name="email" type="email" disabled />
Just checking if this is intended, since the user won't be allowed to update email.

2024-10-05 16:24 UTC, chiaryan commented on apps/frontend/src/app/profile/page.tsx
> +                      }}
I don't think it's enough to just disable the form when cancelling. The user would also expect the values in the form fields to revert to the original values. You'll probably need to store the fetched values somewhere so that you can reset the values when the user cancels.

2024-10-05 17:00 UTC, bensohh commented on apps/frontend/src/app/profile/page.tsx
> +                      }}
Yupp, settled this in the new commit

2024-10-05 17:01 UTC, bensohh commented on apps/frontend/src/app/profile/page.tsx
> +                    <Input name="email" type="email" disabled />
Initially, I wanted to save the trouble by disabling email since it should be the unique identifier but since user-service has already implemented the error handling, I have allowed this field and included necessary error notifications if a duplicated username/email is used

2024-10-06 04:35 UTC, chiaryan commented on apps/frontend/src/app/profile/page.tsx
> +                      }}
LGTM now, thanks!!

2024-10-06 04:36 UTC, chiaryan approved these changes

2024-10-06 04:55 UTC, merged