Sean/auth guard 2
CS3219-AY2425S1/cs3219-ay2425s1-project-g24 pull request #28
Opened 2024-10-05 09:11 UTC by UnwilledTangent

2024-10-05 14:56 UTC, chiaryan reviewed
Hi Sean,

This implementation works for me, but I'm not sure why the `useLayoutEffect` is needed for to redirect the user. Doing this directly in the component body does the redirect also.

```js
if(!isAuthenticated){
  redirect("/login")
}
```

2024-10-05 17:08 UTC, bensohh requested changes
I see that you want to use useLayoutEffect which is a nice attempt. I think you can also look into the comments given regarding writing an AuthProvider

2024-10-05 17:08 UTC, bensohh commented on apps/frontend/src/utils/Auth.ts
> +export const isAdmin = true;
Hmm I think for this right, you can implement all these via an AuthProvider following something similar to https://dev.to/sanjayttg/jwt-authentication-in-react-with-react-router-1d03 instead of via a constant. Then you can try integrating it with the login page logic and wrapping the protected pages components with a ProtectedRoute component

2024-10-06 07:30 UTC, UnwilledTangent commented on apps/frontend/src/utils/Auth.ts
> +export const isAdmin = true;
yeah, wanted to wait for solomon to implement the jwt authentication

2024-10-06 13:18 UTC, UnwilledTangent commented
newer pull request at sean/auth guard 4

2024-10-06 13:18 UTC, closed without merging