Solomon/code execute
CS3219-AY2425S1/cs3219-ay2425s1-project-g24 pull request #62
Opened 2024-11-01 14:54 UTC by solomonng2001

# Execution Service

### Installation

1. Install dependencies:

```bash
go mod tidy
```

2. Create the `.env` file from copying the `.env.example`, and copy the firebase JSON file into execution-service/ fill in the `FIREBASE_CREDENTIAL_PATH` with the path of the firebase credential JSON file.

### Running the Application

To start the server, run the following command:

```bash
go run main.go
```

The server will be available at http://localhost:8083.

## Running the Application via Docker

To run the application via Docker, run the following command:

```bash
docker build -t execution-service .
```

```bash
docker run -p 8083:8083 --env-file .env -d execution-service
```

The server will be available at http://localhost:8083.

## API Endpoints

- `POST /tests/populate`
- `GET /tests/{questionDocRefId}/`
- `POST /tests/{questionDocRefId}/execute`
- `POST /tests/{questionDocRefId}/submit`

## Managing Firebase

To reset and repopulate the database, run the following command:

```bash
go run main.go
```

## Repopulate test cases

To repopulate test cases, you need to repopulate the questions in the question-service, which will automatically call the execution-service to populate the test cases.

In question-service, run the following command:

```bash
go run main.go -populate
```

## API Documentation

`GET /tests/{questionDocRefId}/`

To read visible test cases via a question ID, run the following command:

```bash
curl -X GET http://localhost:8083/tests/{questioinDocRefId}/ \
-H "Content-Type: application/json"
```

The following json format will be returned:

```json
[
   {
      "input":"hello",
      "expected":"olleh"
   }
]
```

`POST /tests/{questionDocRefId}/execute`

To execute test cases via a question ID without custom test cases, run the following command, with custom code and language:

```bash
curl -X POST http://localhost:8083/tests/{questioinDocRefId}/execute \
-H "Content-Type: application/json" \
-d '{
"code": "name = input()\nprint(name[::-1])",
"language": "Python"
}'
```

The following json format will be returned:

```json
{
  "visibleTestResults":[
    {
      "input":"hello",
      "expected":"olleh",
      "actual":"olleh",
      "passed":true,
      "error":""
    }
  ],
  "customTestResults":null
}
```

To execute visible and custom test cases via a question ID with custom test cases, run the following command, with custom code, language and custom test cases:

```bash
curl -X POST http://localhost:8083/tests/{questioinDocRefId}/execute \
-H "Content-Type: application/json" \
-d '{
"code": "name = input()\nprint(name[::-1])",
"language": "Python",
"customTestCases": "2\nHannah\nhannaH\nabcdefg\ngfedcba\n"
}'
```

The following json format will be returned:

```json
{
  "visibleTestResults":[
    {
      "input":"hello",
      "expected":"olleh",
      "actual":"olleh",
      "passed":true,
      "error":""
    }
  ],
  "customTestResults":[
    {
      "input":"Hannah",
      "expected":"hannaH",
      "actual":"hannaH",
      "passed":true,
      "error":""
    },
    {
      "input":"abcdefg",
      "expected":"gfedcba",
      "actual":"gfedcba",
      "passed":true,
      "error":""
    }
  ]
}
```

`POST /tests/{questionDocRefId}/submit`

To submit a solution and execute visible and hidden test cases via a question ID, run the following command, with custom code and language:

```bash
curl -X POST http://localhost:8083/tests/{questioinDocRefId}/submit \
-H "Content-Type: application/json" \
-d '{
"title": "Example Title",
"code": "name = input()\nprint(name[::-1])",
"language": "Python",
"user": "user123",
"matchedUser": "user456",
"matchedTopics": ["topic1", "topic2"],
"questionDifficulty": "Medium",
"questionTopics": ["Loops", "Strings"]
}'
```

The following json format will be returned:

```json
{
  "visibleTestResults":[
    {
      "input":"hello",
      "expected":"olleh",
      "actual":"olleh",
      "passed":true,
      "error":""
    }
  ],
  "hiddenTestResults":{
    "passed":2,
    "total":2
  },
  "status":"Accepted"
}
```

If compilation error exists or any of the tests (visible and hidden) fails, status "Attempted" will be returned:

```json
{
  "visibleTestResults":[
    {
      "input":"hello",
      "expected":"olleh",
      "actual":"",
      "passed":false,
      "error":"Command execution failed: Traceback (most recent call last):\n  File \"/tmp/4149249165.py\", line 2, in \u003cmodule\u003e\n    prit(name[::-1])\n    ^^^^\nNameError: name 'prit' is not defined. Did you mean: 'print'?\n: %!w(*exec.ExitError=\u0026{0x4000364678 []})"
    }
  ],
  "hiddenTestResults":{
    "passed":0,
    "total":2
  },
  "status":"Attempted"
}
```

## TODOs
- Add validation to API endpoints
- Add validation to test cases in database which will be used to validate the custom test cases

2024-11-04 02:25 UTC, tituschewxj approved these changes
LGTM! Thanks for implementing the code execution service. Once the comments are addressed you can merge this PR, as we still need to integrate the other changes together.

We probably can work on the message queuing after this week's demo as we don't want to cause potential issues with deployment.

However, there may be an issue when repopulating the questions as it overwrites the `questionDocRefId` with random values each time, which affects other services as they depend on this value being the same.

2024-11-04 02:25 UTC, tituschewxj commented on apps/execution-service/handlers/execute.go
> +	iter := s.Client.Collection("tests").Where("questionDocRefId", "==", questionDocRefId).Limit(1).Documents(ctx)
We should add `defer iter.Stop()` on a firestore `DocumentIterator` so that we release the resources and avoid resource leaks.

2024-11-04 02:25 UTC, tituschewxj commented on apps/execution-service/handlers/submit.go
> +	json.NewEncoder(w).Encode(testResults)
We might need to adjust these afterwards as there are some changes in the endpoints in the history service in https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g24/pull/60

2024-11-04 02:25 UTC, tituschewxj commented on .github/workflows/test.yml
> +          echo "NEXT_PUBLIC_EXECUTION_SERVICE_URL=$SIGNALLING_SERVICE_URL" >> .env
We should also add this to the .env.example file `NEXT_PUBLIC_EXECUTION_SERVICE_URL="http://localhost:8083/"`

2024-11-04 02:25 UTC, tituschewxj commented on apps/frontend/src/app/collaboration/[id]/page.tsx
> +        questionDocRefId,
There may be a potential problem with `questionDocRefId`, which is whenever the function in `apps/question-service/utils/populate.go` is run, all the `questionDocRefId` are reinitialized to random values, which affects the retrieval of records that utilize this field as an index.

We can either ensure that `questionDocRefId` remains the same when updating the DB, or use something else to identify a question.

2024-11-05 06:44 UTC, UnwilledTangent requested changes

2024-11-05 06:44 UTC, UnwilledTangent commented on apps/execution-service/.env.example
> +HISTORY_SERVICE_URL=http://history-service:8082/
The port number for the HISTORY_SERVICE_URL should be 8083 correct?

2024-11-05 06:45 UTC, UnwilledTangent commented on apps/execution-service/.env.example
> +HISTORY_SERVICE_URL=http://history-service:8082/
(sorry, I accidentally blocked merge)

2024-11-05 09:08 UTC, solomonng2001 commented on apps/execution-service/.env.example
> +HISTORY_SERVICE_URL=http://history-service:8082/
Yes, port for execution service is 8083

2024-11-05 09:11 UTC, UnwilledTangent approved these changes

2024-11-05 09:11 UTC, merged